#!/bin/bash
#
repository="$1"
contextDirectory="$2"

registry=""
platformList="linux/amd64,linux/arm64,linux/arm/v7"

# Calculated settings
gitBranch=$(git branch --show-current)
gitVersion=$(git describe)
imageName="${registry:+${registry}/}${repository}"

case "${gitBranch}" in
	(master)
		docker buildx build \
			--platform "${platformList}" \
			--pull \
			--tag "${imageName}:${gitVersion}" \
			--tag "${imageName}" \
			--push \
			"${contextDirectory}"
		;;
	(*)
		docker buildx build \
			--platform "${platformList}" \
			--pull \
			--tag "${imageName}:snapshot" \
			--push \
			"${contextDirectory}"
		;;
esac
