---
version: "3.6"

secrets:
  # The management user
  amqp.admin.user:
    file: "secret.amqp.admin.user"
  amqp.admin.password:
    file: "secret.amqp.admin.password"
  # The user with which the amr client connects to the AMQP
  amqp.amr.client.user:
    file: "secret.amqp.amr.client.user"
  amqp.amr.client.password:
    file: "secret.amqp.amr.client.password"
  # The user with which the amr server connects to the AMQP
  amqp.amr.server.user:
    file: "secret.amqp.amr.server.user"
  amqp.amr.server.password:
    file: "secret.amqp.amr.server.password"
  # The user with which the shovel connects to the AMQP to read the client messages
  amqp.shovel.client.user:
    file: "secret.amqp.shovel.client.user"
  amqp.shovel.client.password:
    file: "secret.amqp.shovel.client.password"
  # The user with which the shovel connects to the AMQP to write the messages to the server
  amqp.shovel.server.user:
    file: "secret.amqp.shovel.server.user"
  amqp.shovel.server.password:
    file: "secret.amqp.shovel.server.password"
  # Access to DirectAdmin for DNS administration
  certbot.directadmin.url:
    file: "secret.certbot.directadmin.url"
  certbot.directadmin.username:
    file: "secret.certbot.directadmin.username"
  certbot.directadmin.password:
    file: "secret.certbot.directadmin.password"

volumes:
  amqp-data:
  certbot-config:
  certbot-work:

networks:
  net:
    driver: "overlay"

services:
  amqp:
    build:
      context: "./amqp"
    image: "amr-server-amqp"
    hostname: "amr-server"
    secrets:
      - "amqp.admin.user"
      - "amqp.admin.password"
      - "amqp.amr.client.user"
      - "amqp.amr.client.password"
      - "amqp.amr.server.user"
      - "amqp.amr.server.password"
      - "amqp.shovel.client.user"
      - "amqp.shovel.client.password"
      - "amqp.shovel.server.user"
      - "amqp.shovel.server.password"
    environment:
      RABBITMQ_DEFAULT_USER_FILE: "/run/secrets/amqp.admin.user"
      RABBITMQ_DEFAULT_PASS_FILE: "/run/secrets/amqp.admin.password"
    volumes:
      - "amqp-data:/var/lib/rabbitmq"
    networks:
      - "net"
    ports:
      # amqp
      - "5672:5672"
      # http
      - "15672:15672"
      # clustering
      # "25672:25672"

  certbot:
    build:
      context: "./certbot"
    image: "amr-server-certbot"
    secrets:
      - "certbot.directadmin.url"
      - "certbot.directadmin.username"
      - "certbot.directadmin.password"
    volumes:
      - "certbot-config:/etc/letsencrypt"
      - "certbot-work:/var/lib/letsencrypt"
    networks:
      - "net"

  nginx:
    build:
      context: "./nginx"
    image: "amr-server-nginx"
    networks:
      - "net"
    ports:
      # http
      - "80:80"
